config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :index]
      resources :likes, only: [:create]
    end
  end

  delete '/users/:user_id/posts/:post_id', to: 'posts#destroy', as: 'delete_user_post'
  post '/users/:user_id/posts/:post_id/comments', to: 'comments#create', as: 'create_user_post_comment'
  delete '/users/:user_id/posts/:post_id/comments/:comment_id', to: 'comments#destroy', as: 'delete_user_post_comment'

  namespace :api do
    get "/users/:user_id/posts", to: "posts#index", as: "user_posts_api"
    get "/users/:user_id/posts/:post_id/comments", to: "comments#index", as: "post_comments_api"
    post "/users/:user_id/posts/:post_id/comments", to: "comments#create", as: "create_comment_api"
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    can :read, Post

    return unless user.present?

    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
    can :manage, Like, author_id: user.id
    return unless user.admin?

    can :manage, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :comments_counter
  after_destroy :comments_counter

  private

  def comments_counter
    if destroyed?
      post.decrement!(:comments_counter)
    else
      post.increment!(:comments_counter)
    end
  end
end

app/models/current_user.rb
class CurrentUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, class_name: 'Post', foreign_key: 'post_id'

  after_save :likes_counter
  after_destroy :likes_counter

  private

  def likes_counter
    if destroyed?
      post.decrement!(:likes_counter)
    else
      post.increment!(:likes_counter)
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, foreign_key: 'post_id', dependent: :destroy
  has_many :comments, foreign_key: 'post_id', dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :posts_counter
  after_destroy :posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def posts_counter
    if destroyed?
      author.decrement!(:posts_counter)
    else
      author.increment!(:posts_counter)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/application_controller.rb
class Api::ApplicationController < ActionController::API
  respond_to :json
end

app/controllers/api/comments_controller.rb
class Api::CommentsController < Api::ApplicationController
  def index
    @comments = Comment.all.where(author_id: params.require(:user_id), post_id: params.require(:post_id))
    render json: @comments
  end

  def create
    request_body = JSON.parse(request.body.read)
    comment = Comment.new(author_id: User.first, post_id: params.require(:post_id), text: request_body['comment'])
    render json: comment, status: :created
  end

  private

  def comment_body
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/posts_controller.rb
class Api::PostsController < Api::ApplicationController
  def index
    @posts = Post.all.where(author_id: params.require(:user_id))
    render json: @posts, status: :ok
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :photo, :bio, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :photo, :bio, :email, :password, :current_password)
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
    @user = @post.author
  end

  def index
    @comments = Comment.all.where(author_id: params.require(:user_id), post_id: params.require(:post_id))
  end

  def create
    @comment = Comment.new(comments_params)
    @comment.author = current_user
    @comment.post = Post.find(params[:post_id])
    if @comment.save
      redirect_to user_post_path(@comment.post.author, @comment.post)
    else
      render :new
    end
  end

  def destroy
    Comment.find_by(id: params[:comment_id]).destroy
    return render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false if @comment.nil?

    redirect_to user_post_path(@user, params[:post_id])
    if @comment.destroy
      flash[:notice] = 'Comment deleted successfully'
    else
      flash[:alert] = ['Comment not deleted']
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new
    @like.author = current_user
    @like.post = Post.find(params[:post_id])
    if @like.save
      redirect_back(fallback_location: root_path)
    else
      render :new
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource param_method: :post_params, only: %i[create]

  def show
    @post = Post.includes(comments: :author).find_by(author_id: params[:user_id], id: params[:id])
    @comments = @post.comments.includes(:author)
  end

  def index
    @user = User.find(params[:user_id])
    @posts = Post.where(author_id: params[:user_id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0
    @post.author = current_user
    if @post.save
      redirect_to user_posts_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find_by(author_id: params[:user_id], id: params[:post_id])
    return render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false if @post.nil?

    if @post.destroy
      redirect_to user_posts_path(current_user)
    else
      redirect_to user_post_path(current_user, @post)
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find_by(id: params[:id])
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/index.html.erb
<div class="users-container">
  <div class="comment-box">
    <% @comments.each do |comment|%>
      <h3 class="comments"><%= comment.author.name %>:  <%= comment.text %></h3>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="form_post">

<%= form_with model: @comment, url: create_user_post_comment_url, method: :post, local: true, scope: :comment do |form| %>
<%= form.text_area :text, class: "comment_text", placeholder: "Type your comment here..." %>
<%= form.submit "Create", class: "form_btn" %>
<% end %>
</div>

app/views/layouts/_navbar.html.erb
<header>
    <nav>
        <ul class="nav_list">
            <li><%= link_to "Home", users_path, class: "nav-title" %></li>
            <% if user_signed_in? %>
            <li><p class="nav_name">Welcome <%= current_user.name%></p></li>
            <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-btn"  %></li>
            <% else %>
            <li><%= button_to "Sign In", new_user_session_path, class: "nav-btn"  %></li>
            <% end %>
        </ul>
    </nav>
</header>   

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPost</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
  <%= render "layouts/navbar" %>
      <div class="notice" id="notice_message">
        <p class="notice" ><%= notice %></p>
        <p class="alert" ><%= alert %></p>
      </div>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="posts-container">

    <div class="user-box">
        <img class="user-img" src=<%= @user.photo%> alt="user"/>
        <div class="user-info-box">
            <h2 class="user-name"><%= @user.name %></h2>
            <p class="user-post-count">Number of posts: <%= @user.posts_counter%></p>

        </div>
    </div>

    <% @posts.each do |post| %>
        <div class="user-recent-post">
        <%= link_to user_post_path(@user.id, post.id), class:"post_text" do %> 
            <h2 class="user-post-title">Post: #<%= post.title %></h2>
            <% end %>
            <p class="user-post-text"><%= post.text %></p>
            <h3 class="counter">Comments: <%= post.comments_counter%>, Likes: <%= post.likes_counter %><h3>

            <div class="comment_container">
                <% post.recent_comments.each do |comment|%>
                    <h3 class="comments"><%= comment.author.name %>:     <%= comment.text %></h3>
                <% end %>
            </div>
            <div class="like_comment">
                <%= form_with url: user_post_likes_path(current_user, post) do |form| %>
                    <%= form.submit "Like", class: "btn" %>
                <% end %>
                <%= link_to new_user_post_comment_path(current_user, post), class:"link-dec" do %>
                    <button class="btn_comment">Comment</button>
                <% end %>
            </div>
        </div>
    <% end%>

    <button class="button">
        Pagination
    </button>

</div>

app/views/posts/new.html.erb
<div class="posts-container">
  <h1>Add a new post</h1>
  <div class="form_post">
  <%= form_with(model: [ current_user, @post ]) do |form| %>
      <%= form.text_field :title, class: "form_title", placeholder: "Title", required: true %>
      <%= form.text_area :text, class: "form_text", placeholder: "Type your post here...", required: true %>
      <%= form.submit "Create", class: "form_btn" %>
      <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="users-container">
    <div class="user-recent-post">
        <div class="post-inf-box">
            <h2 class="user-post-title">Post: #<%= @post.title %> by <%= @post.author.name %></h2>
            <h3>Comments: <%= @post.comments_counter%>, Likes: <%= @post.likes_counter %><h3>
        </div>
        <p class="user-post-text"><%= @post.text %></p>

        </div>
        <div class="comment-box">
            <% @comments.each do |comment|%>
                <h3 class="comments"><%= comment.author.name %>:  <%= comment.text %></h3>
            <% if can? :delete, comment %>
                <%= button_to 'Delete comment', delete_user_post_comment_path(current_user, @post, comment), class: "btn_delete_comment", method: :delete %>
                <% end %>
            <% end %>
        </div>
  </div>
  <% if can? :delete, @post %>
    <%= button_to 'Delete post', delete_user_post_path(current_user, @post), class:"btn_delete_post", method: :delete %>
  <% end %>
</div>

app/views/users/index.html.erb
<div class="users-container">
    <h1 class="users-heading">Users Count <%= @users.length%></h1>
    <% @users.each do |user| %>
        <%= link_to user_path(user.id), class:"text-dec" do %>
        <div class="user-box">
            <img class="user-img" src="<%= user.photo %>" alt=<%= user.name %>/>
            <div class="user-info-box">
                <h2 class="user-name"><%= user.name %></h2>
                <p class="user-post-count">Number of posts: <%= user.posts_counter%></p>
            </div>
        </div>
        <% end%>
        <% end %>
        <%= link_to new_user_post_path(current_user), class:"text-dec" do %>
        <button class="button">Create a post</button>
        <% end %>
</div>

app/views/users/show.html.erb
<div class="users-container">
    <div class="user-box">
        <img class="user-img" src="<%= @user.photo %>" alt="user"/>
        <div class="user-info-box">
            <h2 class="user-name"><%= @user.name %></h2>
            <p class="user-post-count">Number of posts: <%= @user.posts_counter%></p>
        </div>
    </div>

    <div class="user-bio">
        <p>Bio</p> <br/>
        <p><%= @user.bio %></p>
    </div>


    <% @user.recent_posts.each do |post| %>
        <%= link_to user_post_path(@user.id, post.id), class:"text" do %> 
        <div class="user-recent-post">
            <h2 class="user-post-title">Post : <%= post.title %></h2>
            <p class="user-post-text"><%= post.text %></p>
            <h3 class="user-post-counters">Comments: <%= post.comments_counter%>, Likes: <%= post.likes_counter %><h3>
            </div>
            <% end %>
            <div class="like_comment">
                <%= form_with url: user_post_likes_path(current_user, post) do |form| %>
                    <%= form.submit "Like", class: "btn" %>
                <% end %>
                <%= link_to new_user_post_comment_path(current_user, post), class:"text-dec" do %>
                    <button class="btn_comment">Comment</button>
                <% end %>
            </div>
    <% end%>

    <button class="button">
        <%= link_to "See all posts", user_posts_path(@user), class:"text-dec" %>
    </button>
</div>